### ISSUE TITLE
Global image matrix issue

### ISSUE THREAD

**Issue by qiuhuaqi** [menzelab/implicit-shape-reconstruction#1]
Hi, I'm trying to run the code with Verse'19 data that I downloaded from their github repository.
The data-loading function threw this error: 

```
ValueError: Local to global image matrix is supposed to be 4x4, have scaling and translation components only, and positive scaling. 
```

It looks like most of the image-to-world transformation matrices are not passing the check. What am I doing wrong? Is there any pre-processing I need to do to the data before running your code?

**Comment by aTamaz** [comment]
Hi! Yes, the affine matrices that transform array indices (i,j,k) to (x,y,z) coordinates (in the LPS coordinate system) have negative scaling and/or rotations for most of Verse19 volumes. For simplicity, in the code I assume that the scaling is positive and that there is no rotation (this assumption should not be too hard to change if needed). In other words, I assume that array indices i,j,k (roughly) align with anatomical axes left-to-right, posterior-to-anterior, and superior-to-inferior (LPS).

Therefore, as pre-processing I transpose & flip the arrays so that the resulting affine matrix has positive scaling and so that array indices i,j,k map to anatomical axes L, P and S. The remaining small rotations are disregarded. Note that this is done automatically.

Furthermore, individual vertebrae are extracted from the multi-label segmentations to obtain binary segmentation masks with one vertebra each. Note that I've only used lumbar vertebra from scans with (originally) isotropic spacing for a unified experimental setup.

I've included the script I've used into the repo:

https://github.com/menzelab/implicit-shape-reconstruction/blob/main/preprocessing/extract_vertebra.py

The OAI-ZIB Femur dataset is a bit easier to use, since there I've directly used the labels without any pre-processing.

**Comment by qiuhuaqi** [comment]
Thank you for your answer and the preprocessing script! It does work well on the Versa19 data.

I might be missing something basic here. I still don't understand the purpose of changing the image-to-world matrix and the corresponding data array flipping (normalising the coordinates). For the purpose of evaluating the method, if we are predicting in the image space, why do we need to align the ijk coordinate and the LPS coordinates?

**Comment by aTamaz** [comment]
The label volumes in Verse19 have different orientations, so the anatomies will be misaligned if you don't transpose/flip. Apart from that, it does not really matter, where i,j,k are pointing -- as long as it is consistent. Hope that helps!

**Comment by qiuhuaqi** [comment]
@aTamaz Ah I got it now. Indeed this is what I'm trying to understand so I can make sure if the same applies to my own dataset. Thank you very much!
